# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: zipkin-ingress
#   annotations:
#     cert-manager.io/issuer: "letsencrypt-prod"
#     nginx.ingress.kubernetes.io/auth-type: basic
#     nginx.ingress.kubernetes.io/auth-secret: zipkin-secret
#     nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
# spec:
#   ingressClassName: nginx
#   tls:
#     - hosts:
#         - {{ deployment.host }}
#       secretName: pinklifeline-tls
#   rules:
#     - host: {{ deployment.host }}
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: zipkin
#                 port:
#                   number: 9411