name: 'Terraform Deploy'

on:
#   push:
#     branches:
#       - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: echo "Sadi"

      - name: Setup Google Cloud SDK
        uses: 'google-github-actions/auth@v2'
        with:
            credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        working-directory: ./prod
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Plan
        id: plan
        working-directory: ./prod
        run: terraform plan
        env:
          TF_VAR_database_user_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_database_user_password: ${{ secrets.DB_PASS }}
          TF_VAR_email_password: ${{ secrets.EMAIL_PASS }}
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        continue-on-error: true